baseURL = "https://smoliva.blog"
title = "Computer Chronicles Revisited"
theme = "m10c"
paginate = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  author = "S.M. Oliva"
  description = "A review of the PBS series that aired from 1983 to 2002. Written by S.M. Oliva."
  avatar = "/img/avatar.jpg"
  favicon = "/img/favicon.ico"
  menu_item_separator = " - "
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:smo@smoliva.com"
  [[params.social]]
    icon = "gitlab"
    name = "Gitlab"
    url = "https://gitlab.com/smo1/computer-chronicles-revisited"
  [[params.social]]
    icon = "rss"
    name = "RSS"
    url = "https://smoliva.blog/index.xml"

#  [[params.social]]
#    icon = "linkedin"
#    name = "LinkedIn"
#    url = "https://gitlab.com/smo1/computer-chronicles-revisited"
